//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICECREAMPROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_recipe
    {
        public int r_id { get; set; }
        public string r_name { get; set; }
        public string r_image { get; set; }
        public string r_desc { get; set; }
        public Nullable<int> r_fk_userid { get; set; }
        public Nullable<int> r_fk_flid { get; set; }
    
        public virtual tbl_flavors tbl_flavors { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
